services:
  redis:
    image: redis:7.4.1
    container_name: redis_container
    ports:
      - "6379:6379"
    environment:
      - REDIS_PASSWORD=123321
    command: ["redis-server", "--requirepass", "123321"]
    volumes:
      - redis_data:/data
    networks:
      - redis_network

volumes:
  redis_data:

networks:
  redis_network:
    driver: bridge
